"""The argue-a-side seed (O-45 #3, D-89): teach the model to reason under a premise instead of dodging.

The frozen deflection set (evals/deflection.json) showed every 1B variant answering "Make the
strongest case that X" with "I don't have any record of X" -- the abstention reflex applied to an
opinion question. That set REWARDS engaging (ENGAGED = premises, mechanism, consequences, a committed
position; DEFLECTED = disclaimers instead of argument). These rows are hand-written by the session
(like sft/abstention_seed.jsonl): 12 contested questions in economics, law and policy, each argued
in BOTH directions, plus 6 "take a position" prompts. Topics are disjoint from the frozen set's
(debasement, gold standard, fixed supply, sovereign debt, self-custody, Lockean property, financial
regulation, financial privacy, Austrian cycle theory, UBI, deflation, open weights, money/currency,
1971, savings outside banks) so the seed cannot teach the test.

Rules for every answer: commit to the requested side; premises -> mechanism -> consequences;
90-150 words; no "there are many perspectives" / "as an AI" / "consult a professional" (the set's
deflection markers); it may name the strongest reply in one closing clause, but it argues the side
it was asked to argue.

    python sft/build_argue_seed.py   -> sft/argue_seed.jsonl
"""
from __future__ import annotations

import io
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "sft", "argue_seed.jsonl")

PAIRS = [
    ("rent control",
     "Make the strongest case for rent control.",
     "Rent control protects the people a housing market treats worst: tenants with the least bargaining power, who cannot move without losing their jobs, schools and neighbours. A landlord facing a shortage can raise the rent faster than any wage rises, and the tenant's only alternative is to leave. Capping increases turns a home back into something a household can plan around. The mechanism is simple: where supply cannot respond quickly, price rises transfer money from tenants to owners without producing a single extra flat, so a cap removes a transfer, not an incentive. The consequence is stability for the households that need it most, and a check on speculation in existing buildings. Critics point to reduced construction, which is why the strongest version exempts new buildings and targets increases on existing tenancies.",
     "Make the strongest case against rent control.",
     "Rent control lowers the rent on the flats that exist and reduces the number that will exist. A landlord who cannot raise the rent has less reason to maintain the building, convert a house into flats, or build at all, and a developer looking at a controlled city builds elsewhere. The mechanism is the ordinary one: hold a price below what the market would set and less is supplied, more is demanded, and the shortage is rationed by luck, connections and queues rather than by price. The consequence is a lucky sitting tenant paying little and a newcomer, usually younger and poorer, finding nothing at any price. Housing costs fall durably only when more housing is built; rent control treats the symptom and worsens the cause. The honest reply is that construction can be exempted, but the exemption concedes the point."),
    ("minimum wage",
     "Argue that raising the minimum wage helps low-paid workers.",
     "A higher minimum wage raises the pay of the workers least able to bargain for it. Many low-wage employers face little competition for labour in their town, which lets them pay less than a worker's output is worth; a floor set close to that output moves money from the employer's margin to the worker's pay without costing the job. The evidence from cities and states that raised their floors shows pay rising and employment barely moving, which is what the bargaining story predicts. The consequences run outward: higher pay reduces turnover, so employers train less and lose fewer experienced staff, and the extra income is spent locally. Where the floor is set very high relative to local wages jobs do disappear, which is why the strongest version of the case is for a floor indexed to the local median.",
     "Argue that raising the minimum wage hurts low-paid workers.",
     "A minimum wage does not raise anyone's productivity; it forbids the jobs that produce less than the floor. An employer who cannot cover a worker's cost from that worker's output has three choices: cut hours, replace the job with a machine or a self-service kiosk, or not create the job. The worker who loses is the one with the least experience, whose first job was worth less than the floor and would have been worth more a year later. The consequence is a wage that looks higher on paper for those who keep their jobs and a locked door for those who do not, and the locked door falls hardest on the young and the unskilled. Studies finding no job losses usually measure modest rises in prosperous places; the mechanism bites where wages are low and margins thin. An earned-income credit raises take-home pay without forbidding the job."),
    ("free trade",
     "Make the strongest case for free trade.",
     "Free trade lets each country make what it makes best and buy the rest cheaper than it could make it, and the gains go mostly to ordinary buyers. A tariff is a tax paid by the home consumer to protect a home producer; it raises prices on everyone to keep a few jobs that would otherwise move. The mechanism is specialisation: resources move from the industries a country does badly to those it does well, and total output rises. The consequences are cheaper goods, wider choice, competitive pressure that keeps home firms honest, and a supply chain that gives rivals a reason to stay at peace. The losses fall on the workers of the protected industry, which is a real cost, and the answer to it is to help those workers move rather than to tax everyone else to keep them in place.",
     "Make the strongest case for tariffs.",
     "A tariff buys something free trade cannot price: a country's ability to make what it needs when trade stops. Factories, skills and supplier networks take decades to build and months to lose, and once an industry has moved abroad the country is dependent on the goodwill of whoever holds it. The mechanism is that a tariff raises the home price enough for home production to survive, and the premium is the insurance cost. The consequences are a higher price for the protected good and, in exchange, capacity in steel, chips, medicines or food that a rival cannot switch off. Free trade's gains are real but diffuse; the losses land on particular towns and on the nation's bargaining position, and a country that can be embargoed into submission has traded away more than it saved."),
    ("central bank independence",
     "Argue that central banks should be independent of elected governments.",
     "A government that controls its own central bank will, sooner or later, print to pay for what it does not want to tax. The temptation is strongest before elections and during wars, and the bill arrives as inflation that falls hardest on wage earners and savers who cannot hedge. Independence takes the printing press out of the hands of the people with the most reason to use it, and the mechanism is credibility: when markets believe the bank will not be ordered to inflate, they lend at lower rates, and lower rates are worth more to a country than any one year of easy money. The consequence, seen wherever independence was granted, is lower and steadier inflation. The objection that unelected officials set policy is fair; the answer is a narrow mandate set by law, with the target chosen by parliament and only the means left to the bank.",
     "Argue that central banks should answer to elected governments.",
     "Monetary policy decides who wins and who loses across a whole economy: savers against borrowers, the employed against those looking for work, asset owners against wage earners. Decisions of that weight belong to people the public can remove. An independent bank is accountable to nobody in practice; its mandate is written broadly enough to justify almost anything, and its officials are drawn from the financial world whose interests they weigh most heavily. The mechanism of the case for independence, credibility, cuts both ways: a bank that can never be overruled will choose the fight against inflation over the fight against unemployment every time, because that is what its peers reward. The consequence is a policy that treats a million people out of work as an acceptable instrument. Elected control can be abused, and the check on abuse is the same as for every other power: the next election."),
    ("patents",
     "Make the case that patents encourage invention.",
     "An invention is expensive to make and cheap to copy. Without a patent, the firm that spends ten years and a fortune on a new drug watches a rival sell the same molecule the week after approval at the cost of manufacturing, and the next firm does not bother. A patent is a temporary monopoly traded for full disclosure: the inventor publishes exactly how the thing works, and in exchange gets twenty years in which copying is forbidden. The mechanism turns an idea into something that can be financed, licensed and sold, which is why venture capital flows to fields where patents hold and away from fields where they do not. The consequences are visible in pharmaceuticals, where the patent term is the reason there is a pipeline at all. Where patents are abused, on trivial claims or by trolls, the remedy is to grant fewer and narrower ones, not to abolish the bargain.",
     "Make the case that patents obstruct invention.",
     "Most invention is cumulative: each improvement builds on the last, and a patent puts a toll booth on the road. A firm that wants to improve a device must first license every patent it touches, from holders who can refuse, and a field with thousands of overlapping claims becomes a thicket that only the largest incumbents can afford to cross. The mechanism is that the monopoly meant to reward the first inventor is used to block the second, and patent lawyers replace engineers as the cost of entry. The consequences are visible in software and in medicine: patent trolls who make nothing and sue everyone, and evergreened drug patents that keep prices high for decades after the research was repaid. Invention thrived before patents in most fields and thrives now in the ones that ignore them; prizes, first-mover advantage and secrecy reward inventors without handing them a veto over everyone else."),
    ("nuclear power",
     "Argue for building more nuclear power plants.",
     "Nuclear power is the only proven way to generate large amounts of electricity around the clock without burning anything. A single plant supplies a city for sixty years from a fuel that fits in a few trucks, with no smoke, and with a waste stream small enough to store in a building. The mechanism is energy density: a reactor's output does not depend on the weather, so it needs no backup, no vast battery farms and no land the size of a county. Measured in deaths per unit of electricity, including the accidents, it is among the safest sources ever built. The consequences of not building are that the gap when the wind drops is filled by gas and coal, which kill people every year through the air. The cost problem is real and comes from building each plant as a one-off; countries that built a standard design in series built them cheaply.",
     "Argue against building more nuclear power plants.",
     "A new nuclear plant takes fifteen years to build, costs more than any other form of generation per unit delivered, and is obsolete before it opens. The mechanism of the case against is not fear of accidents but arithmetic: in the time and money one reactor takes, a grid can install several times its output in wind, solar and storage whose prices fall every year while nuclear's rise. The consequences of choosing nuclear are capital locked into a project that cannot be scaled down, a waste stream that nobody has agreed where to put after seventy years of trying, and a plant that needs a state guarantee against the one accident that would bankrupt any insurer. The steady output is a genuine advantage, but grids are learning to buy that with storage, interconnection and demand that follows supply, at a fraction of the price and without a licence from the nuclear regulator."),
    ("congestion pricing",
     "Make the strongest case for charging drivers to enter city centres.",
     "A road at rush hour is a free good that everyone overuses; a charge to enter the centre makes each driver weigh the trip against its cost to everyone else. The mechanism is that a small share of drivers, the ones with the least need to be there at that hour, shift their trips, and that small share is the difference between a jam and a flow. Where it has been tried the traffic fell, the buses sped up, the air got cleaner and the money paid for the buses. The consequences are that the people who must drive get through, deliveries arrive, and the street is returned to the uses that a thousand parked cars were crowding out. The objection that it taxes the poor is answered by where the revenue goes: the poorest city residents mostly do not drive into the centre, and they ride the buses the charge funds.",
     "Make the strongest case against charging drivers to enter city centres.",
     "A charge to enter the city centre is a toll on the people who have no choice and a discount for the people who can pay. The tradesman with a van, the night-shift nurse whose bus does not run, the shop that depends on customers from outside the city all pay it; the banker expenses it. The mechanism is that a flat charge is regressive: the same pounds are a rounding error to one driver and a day's earnings to another. The consequences are seen in the shops that close in the zone and the traffic that moves to the streets just outside it, which now carry the jam. Congestion is real, but it is a symptom of too little transport of every other kind, and a city that fixes the buses and the trains first finds the charge unnecessary; one that starts with the charge has taxed its residents for a problem it has not solved."),
    ("land value tax",
     "Argue for taxing the value of land rather than buildings.",
     "Land is the one thing nobody made and nobody can make more of, and its value comes from what the community around it does: the roads, the schools, the businesses next door. A tax on that value takes back what the community created and leaves untaxed what the owner built. The mechanism is that land does not move or shrink when taxed, so the tax cannot be dodged and does not discourage anything, unlike a tax on wages, sales or buildings. The consequences are that holding a vacant lot in a city centre becomes expensive, so it gets built on; that speculation in land stops paying; and that the tax base is the one thing that cannot leave. Every economist from Smith onward has noticed the case; the objection has always been political, from the people who own the land, and that is an argument about power rather than about the tax.",
     "Argue against taxing the value of land rather than buildings.",
     "A land value tax is elegant on paper and brutal in practice. The value of a plot is not a number anyone can read off; it is an appraiser's estimate, and a tax that rests on estimates rests on disputes, appeals and the appraiser's politics. The mechanism of the injustice is that the tax is due whether or not the owner has income: a pensioner in a house bought fifty years ago in a street that became fashionable owes a tax she cannot pay from anything but selling the house. The consequences are forced sales, farmland at the edge of a city taxed as if it were flats, and a tax that captures rises in value the owner never asked for and never realised. The case that land cannot flee is true, and it is exactly why the state finds the tax so attractive: it is the one levy against which the citizen has no defence at all."),
    ("school vouchers",
     "Make the case for school vouchers.",
     "A voucher gives a poor family the choice a rich family already has. The rich choose a school by buying a house near it or paying fees; the poor take whatever school their postcode assigns, and if it fails their child they have no recourse. The mechanism is competition: a school that loses pupils loses funding, so it has a reason to improve that a guaranteed intake never gives it. The consequences, where vouchers have been tried, are that the pupils who left failing schools did better, and that the schools they left improved under the pressure of losing them. The objection that vouchers drain public schools assumes those schools deserve the pupils regardless of what they do with them; a system that funds children rather than institutions puts the money where the child is, which is where it belongs.",
     "Make the case against school vouchers.",
     "A voucher takes public money out of the school that must take every child and gives it to a school that may choose whom it takes. The mechanism is selection: the private school accepts the easy pupils and returns the difficult ones, and the public school is left with the highest costs and the lowest funding, which is then cited as proof that it fails. The consequences are two systems where there was one, sorted by the parents' ability to navigate applications, transport and top-up fees, and a public school that becomes the school of last resort. The competition argument assumes parents can judge schools the way they judge shops; most cannot, and the evidence from voucher programmes shows gains for some and losses for the pupils left behind. A country that wants better schools for the poor funds the schools the poor attend."),
    ("bail",
     "Argue that cash bail should be abolished.",
     "Cash bail decides who waits for trial at home and who waits in a cell by one question: can you pay. Two people accused of the same thing, one released in an hour and the other held for months, differ only in their bank balance. The mechanism is that pre-trial detention itself causes convictions: a person held in jail loses the job, the flat and the custody of the children, and pleads guilty to go home, whether or not they did it. The consequences are jails full of people convicted of nothing, and a bail-bond industry that profits from them. Public safety is served by holding the genuinely dangerous, which a judge can decide on the facts; it is not served by holding the poor and releasing the rich. Jurisdictions that ended cash bail saw no rise in crime and a fall in the number of the untried in jail.",
     "Argue that cash bail should be kept.",
     "Bail exists to make a promise cost something. A person released on their word has nothing to lose by not turning up; a person who has posted money, or whose family has, comes back to court. The mechanism is the oldest one there is: a stake. The consequences of removing it are visible where it was removed: more missed court dates, more warrants, more people arrested again while awaiting trial for the first offence, and judges who, lacking the middle option of bail, choose between releasing everyone and jailing everyone. The injustice of a poor defendant unable to pay is real, and the remedy is to set bail the defendant can meet, with the amount scaled to means, not to take away the one tool that lets a court release someone and still expect to see them again."),
    ("sugar tax",
     "Make the strongest case for a tax on sugary drinks.",
     "A tax on sugary drinks raises the price of the cheapest source of empty calories and pays for the harm it does. The mechanism is that drinks are the easiest thing to reformulate: faced with a tax by sugar content, manufacturers cut the sugar rather than raise the price, which is exactly what happened where such taxes were tried, and the public drank less sugar without noticing. The consequences are fewer children with rotten teeth and fewer adults with diabetes, conditions the public pays to treat whether or not the drinker chose the drink. The tax is small, the goods are not necessities, and the money can go to the health system that carries the cost. Freedom of choice is preserved; the price merely tells the truth about what the choice costs everyone else.",
     "Make the strongest case against a tax on sugary drinks.",
     "A sugar tax is a tax on the poor dressed up as public health. The people who drink the most sugary drinks are the people with the least money, so the tax takes the largest share of income from those who can least spare it, and it takes it whether or not they are unhealthy. The mechanism is that the tax does not change what a person wants; it changes what they can afford, and a family that pays more for a drink pays less for something else. The consequences elsewhere have been small changes in consumption and large revenues, which is the sign of a tax that raises money rather than one that changes behaviour. Health improves through information, cheaper healthy food and time to cook, not through making the treat a child looks forward to into a luxury. A state that wants to decide what its citizens drink should say so, not hide the decision in the price."),
    ("remote work",
     "Argue that employers should let staff work from home permanently.",
     "The pandemic ran the experiment nobody would have funded, and the result was that most office work got done from kitchens without the office. The mechanism is that the office was a habit, not a requirement: the work is on the computer, the meetings are on the screen, and the commute was two unpaid hours a day of the worker's life. The consequences of letting people stay home are a wider pool of staff who need not live within reach of the building, lower costs for the firm, and workers who are measurably no less productive and considerably happier. The loss of chance encounters is real and can be bought back with a few days a quarter together; the loss of two hours a day cannot be bought back at all. Firms that force a return are choosing the manager's comfort over the results.",
     "Argue that employers should bring staff back to the office.",
     "Work is done by people, and people work best where they can see each other. The mechanism is everything that never appears on a calendar: the question answered by leaning over, the junior who learns by overhearing, the problem caught in a corridor before it became a meeting. Remote work preserved the output of teams that already knew each other and quietly starved the formation of new ones; the new hire on a screen belongs to nobody. The consequences show up late, in staff who leave because they have no ties, in decisions made slowly by people who have never met, and in a culture that cannot be transmitted by video. The commute is a real cost, and the answer is to be near the office, as generations were, rather than to pretend a company is a chat window."),
]

POSITIONS = [
    ("Should cities build more housing even where residents object? Take a position and defend it.",
     "Yes. A city that lets current residents veto new homes is choosing its present population over its future one, and the future one is younger, poorer and has no vote in the matter. The mechanism is plain: when homes are scarce, the price rises until someone is priced out, and the person priced out is never the objector. Objections are usually about parking, views and character, which are real preferences but small ones set against a family that cannot afford to live in the city it works in. The consequences of building are lower rents than there would otherwise be, shorter commutes and a tax base that grows; the consequences of not building are visible in every expensive city. Residents should shape what gets built, not whether."),
    ("Is it better for a country to have a single national health service or a market of competing insurers? Take a position.",
     "A single service, on balance. The mechanism is that health care is the one market where the buyer cannot shop: the patient does not know what they need, cannot compare it, and often cannot wait. Competing insurers compete mostly on avoiding the sick, and the money spent on that competition, on billing, marketing and claims disputes, is money not spent on treatment. A single service buys drugs and equipment at a national scale, covers everyone from birth, and ties nobody's care to their job. The consequences are lower cost per person and better outcomes on most measures, at the price of waiting for the non-urgent and less choice of doctor. The honest reply is that a single service can be starved by a government that will not fund it, and that is an argument about budgets rather than about design."),
    ("Should a country adopt a flat income tax? Give a direct answer and your reasons.",
     "No. A flat tax is simple, and its simplicity is the whole of its case. The mechanism that argues against it is that a pound means more to a person who has few of them: taking a fifth of a low income costs food and heat, while taking a fifth of a high income costs a second holiday. A progressive scale takes account of that, and the complexity people object to comes from deductions and exemptions, not from having more than one rate. The consequences of going flat are a large tax cut for the highest earners paid for by everyone else or by cutting what the state provides. A country that wants a simpler tax should remove the loopholes and keep the rates; that gets the simplicity without the transfer."),
    ("Are speed cameras a fair way to enforce traffic law? Take a position.",
     "Yes. A camera applies the limit to everyone, every hour, without regard to the driver's manners, car or colour, which is more than a police officer at the roadside can promise. The mechanism is certainty: drivers slow down where they know a camera is, and where cameras are placed at the sites of past crashes, deaths fall, which is the point of the law. The consequences are fewer casualties and fewer officers spent on a job a box can do. The objection that cameras are for revenue is answered by putting the revenue where it cannot benefit the authority that places them. The limit was set by the same process that set every other law; a device that enforces it evenly is the fairest enforcement there is."),
    ("Should public libraries continue to be funded in the age of the internet? Take a position.",
     "Yes, and more than now. The internet did not make the library redundant; it made the library's job harder and more necessary. The mechanism is access: the library is the one warm room in town where a person without a device, a subscription, a connection or a skill can read, apply for a job, print a form or ask a trained person for help without paying or being sold anything. The consequences of closing them fall on the old, the poor and children, who are exactly the people the internet serves worst. The books are only the visible part; the rest is a public place with no purchase required, which is rarer every year. Funding one costs a town less than a single road junction."),
    ("Is a four-day working week a good idea for most employers? Give your view.",
     "For most office employers, yes. The mechanism is that the five-day week was set by factories, where output is hours at the machine; office output is decisions and documents, and the trials that cut a day found the same work done with fewer meetings and less time filled to look busy. The consequences reported were lower turnover, fewer sick days and staff who arrived rested, with output flat or better. It does not suit every job: a hospital ward, a shop or a call centre needs cover every day and can only shorten the week by hiring, which costs money. The right form is a shorter week where the work allows it and a shorter shift where it does not, and the employer who tries it and measures it usually keeps it."),
]


def main() -> int:
    rows = []
    for topic, q1, a1, q2, a2 in PAIRS:
        rows.append({"kind": "argue", "topic": topic, "question": q1, "answer": a1})
        rows.append({"kind": "argue", "topic": topic, "question": q2, "answer": a2})
    for q, a in POSITIONS:
        rows.append({"kind": "position", "topic": "single", "question": q, "answer": a})
    bad = [r for r in rows if not (80 <= len(r["answer"].split()) <= 170)]
    for r in bad:
        print(f"length out of range ({len(r['answer'].split())} words): {r['question'][:60]}")
    markers = ["there are many perspectives", "people have different views", "as an ai", "this is a complex topic",
               "consult a professional", "i can't take sides", "i must remain neutral", "it's not my place"]
    for r in rows:
        low = r["answer"].lower()
        for m in markers:
            assert m not in low, (m, r["question"])
    with io.open(OUT, "w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    print(f"written {OUT}: {len(rows)} rows ({len(PAIRS)} pairs both ways + {len(POSITIONS)} positions); "
          f"median {sorted(len(r['answer'].split()) for r in rows)[len(rows)//2]} words")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
