"""Verifiable reasoning problems with program-computed keys AND program-written traces (O-45 #3,
Eric's lever #2; D-93 next mix).

Every problem here is generated by a program that also computes the answer and writes the worked
steps, so a training signal needs no teacher and no licence question. Three uses:
  * SFT seed: prompt -> the program's own trace ending in "Answer: <value>" (sft/reasoning_seed_gen.jsonl);
    the 1B measured 0/8 correct on these before any of this existed (2026-09-25), so it has to be
    shown the act before a reward can shape it.
  * GRPO reward (train_grpo.py, kind "reasoning"): +1 only when the model's final answer matches the key.
  * STaR harvest (scripts/star_sample.py): the model's own traces, kept only when the checker agrees.

Eight families, integer answers by construction, so a match is exact:
  shop        n items at a price, a discount or a note to pay with -> total / change
  rate        speed-time-distance, work rates, unit prices (integer results)
  percent     percent of / increase / decrease, chosen so the result is whole
  convert     metric and time conversions (km->m, h->min, weeks->days, ...)
  date        days between two dates, weekday of date + N days, days left in a month
  order       three-to-five-person comparisons (taller / older / faster) -> who is the extreme
  count       small counting: multiples in a range, digits, pages numbered, handshakes
  average     mean of a small list, missing value given a mean, remainder problems

    python sft/build_reasoning_set.py [--n 3000] [--seed 7]
      -> sft/grpo_reasoning.jsonl        {"kind": "reasoning", "family", "prompt", "answer", "unit", "trace"}
      -> sft/reasoning_seed_gen.jsonl    {"kind": "reasoning-gen", "family", "messages": [user, assistant]}

The answer is matched by final-line parsing (answer_matches below), shared with the GRPO reward and
the sampler so the three never disagree. Traces vary their phrasing by template so the fine-tune
learns the act of working it out, not one sentence.
"""
from __future__ import annotations

import argparse
import calendar
import io
import json
import os
import random
import re
from datetime import date, timedelta

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "sft", "grpo_reasoning.jsonl")
OUT_SEED = os.path.join(ROOT, "sft", "reasoning_seed_gen.jsonl")

NAMES = ["Ana", "Ben", "Carla", "Dev", "Elena", "Farid", "Grace", "Hugo", "Iris", "Jonas", "Kira", "Leo",
         "Maya", "Nils", "Omar", "Priya", "Quinn", "Rosa", "Sam", "Tara", "Uma", "Vik", "Wen", "Yara", "Zoe"]
ITEMS = [("notebook", 3, 12), ("pen", 2, 4), ("loaf of bread", 2, 5), ("ticket", 8, 40), ("mug", 4, 15),
         ("apple", 2, 3), ("book", 6, 30), ("candle", 2, 9), ("plant", 5, 25), ("bus ticket", 2, 6)]
PLURAL = {"loaf of bread": "loaves of bread"}
WEEKDAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
ORD_RELATIONS = [("taller", "shorter", "tallest", "shortest"), ("older", "younger", "oldest", "youngest"),
                 ("faster", "slower", "fastest", "slowest"), ("heavier", "lighter", "heaviest", "lightest")]
SUFFIX = " Think it through step by step, then end with 'Answer: <value>'."


def pl(n: int, item: str) -> str:
    return f"{n} {item}" if n == 1 else f"{n} {PLURAL.get(item, item + 's')}"


def dmy(d: date) -> str:
    return d.strftime("%d %B %Y").lstrip("0")


# ---- the shared matcher: final answer = the LAST number (or word) in the text, after "Answer:" if present ----
def final_answer(text: str) -> str:
    """The model's final answer: what follows the last 'Answer:' if any, else the last number in the text."""
    t = text.strip()
    m = list(re.finditer(r"(?i)answer\s*[:=]\s*([^\n]+)", t))
    if m:
        t = m[-1].group(1)
    nums = re.findall(r"-?\d[\d,]*(?:\.\d+)?", t)
    if nums:
        return nums[-1].replace(",", "")
    words = re.findall(r"[A-Za-z]+", t)
    return words[-1] if words else ""


def answer_matches(text: str, answer: str) -> bool:
    got = final_answer(text)
    if not got:
        return False
    if re.fullmatch(r"-?\d+(?:\.\d+)?", answer):
        try:
            return abs(float(got) - float(answer)) < 1e-6
        except ValueError:
            return False
    return got.lower() == answer.lower()


def fin(r, steps: list[str], ans: str, unit: str = "") -> str:
    """Join the worked steps and close with the answer line, varying the connective."""
    lead = r.choice(["", "Step by step: ", "Working it out: ", "Let me work through it. "])
    close = r.choice(["So the answer is", "That gives", "Therefore", "So"])
    u = f" {unit}" if unit else ""
    return f"{lead}{' '.join(steps)} {close} {ans}{u}.\nAnswer: {ans}"


# ---- families: each returns (question, answer, unit, trace) ----------------------------------------------
def f_shop(r):
    n1 = r.randint(2, 9); it1, lo, hi = r.choice(ITEMS); p1 = r.randint(lo, hi)
    who = r.choice(NAMES); v = r.random()
    if v < 0.4:
        n2 = r.randint(1, 6); it2, lo2, hi2 = r.choice([i for i in ITEMS if i[0] != it1]); p2 = r.randint(lo2, hi2)
        total = n1 * p1 + n2 * p2
        q = f"{who} buys {pl(n1, it1)} at {p1} dollars each and {pl(n2, it2)} at {p2} dollars each. How much is that in total, in dollars?"
        tr = fin(r, [f"{pl(n1, it1)} at {p1} dollars each cost {n1} × {p1} = {n1*p1} dollars.",
                     f"{pl(n2, it2)} at {p2} dollars each cost {n2} × {p2} = {n2*p2} dollars.",
                     f"Together: {n1*p1} + {n2*p2} = {total}."], str(total), "dollars")
        return q, str(total), "dollars", tr
    if v < 0.7:
        total = n1 * p1; note = next(x for x in (20, 50, 100, 200, 500) if x >= total + 1)
        q = f"{who} buys {pl(n1, it1)} at {p1} dollars each and pays with a {note}-dollar note. How much change is due, in dollars?"
        tr = fin(r, [f"The {PLURAL.get(it1, it1 + 's')} cost {n1} × {p1} = {total} dollars.",
                     f"Change from {note} dollars: {note} - {total} = {note-total}."], str(note - total), "dollars")
        return q, str(note - total), "dollars", tr
    total = n1 * p1; off = r.choice([d for d in (5, 10, 20, 25, 50) if (total * d) % 100 == 0] or [50])
    disc = total * off // 100
    q = f"{pl(n1, it1)} cost {p1} dollars each, and the shop takes {off} percent off the total. What is the price after the discount, in dollars?"
    tr = fin(r, [f"Before the discount: {n1} × {p1} = {total} dollars.",
                 f"{off} percent of {total} is {total} × {off}/100 = {disc}.",
                 f"After the discount: {total} - {disc} = {total-disc}."], str(total - disc), "dollars")
    return q, str(total - disc), "dollars", tr


def f_rate(r):
    v = r.random(); who = r.choice(NAMES)
    if v < 0.35:
        sp = r.choice([30, 40, 45, 50, 60, 80]); h = r.randint(2, 7)
        tr = fin(r, [f"Distance is speed times time: {sp} km/h × {h} h = {sp*h} km."], str(sp * h), "kilometres")
        return f"A train travels at {sp} kilometres per hour for {h} hours. How far does it go, in kilometres?", str(sp * h), "km", tr
    if v < 0.6:
        sp = r.choice([4, 5, 6, 8, 10, 12]); d = sp * r.randint(2, 9)
        tr = fin(r, [f"Time is distance divided by speed: {d} km / {sp} km/h = {d//sp} hours."], str(d // sp), "hours")
        return f"{who} cycles {d} kilometres at a steady {sp} kilometres per hour. How many hours does it take?", str(d // sp), "hours", tr
    if v < 0.8:
        per = r.randint(2, 9); mins = r.choice([10, 15, 20, 30, 60]); total = mins * r.randint(2, 6); k = total // mins
        tr = fin(r, [f"{total} minutes holds {total} / {mins} = {k} periods of {mins} minutes.",
                     f"Each period makes {per} parts, so {k} × {per} = {k*per}."], str(k * per), "parts")
        return f"A machine makes {per} parts every {mins} minutes. How many parts does it make in {total} minutes?", str(per * k), "parts", tr
    n = r.randint(2, 8); unit = r.randint(2, 15); total = n * unit; it = r.choice(ITEMS)[0]
    tr = fin(r, [f"{n} of them cost {total} dollars, so one costs {total} / {n} = {unit}."], str(unit), "dollars")
    return f"{pl(n, it).replace(' ', ' identical ', 1)} cost {total} dollars altogether. What does one cost, in dollars?", str(unit), "dollars", tr


def f_percent(r):
    v = r.random()
    p = r.choice([5, 10, 15, 20, 25, 30, 40, 50, 60, 75, 80])
    from math import gcd
    step = 100 // gcd(p, 100)                  # the smallest base that keeps p percent of it whole
    base = step * r.randint(max(1, 20 // step), 2000 // step)
    x = base * p // 100
    if v < 0.4:
        tr = fin(r, [f"{p} percent means {p} out of 100: {base} × {p}/100 = {x}."], str(x))
        return f"What is {p} percent of {base}?", str(x), "", tr
    if v < 0.7:
        tr = fin(r, [f"{p} percent of {base} is {base} × {p}/100 = {x}.", f"The new price is {base} + {x} = {base+x}."], str(base + x), "dollars")
        return f"A jacket costs {base} dollars. Its price goes up by {p} percent. What is the new price, in dollars?", str(base + x), "dollars", tr
    tr = fin(r, [f"{p} percent of {base} is {base} × {p}/100 = {x}.", f"Fewer by {x}: {base} - {x} = {base-x}."], str(base - x), "shops")
    return f"A town had {base} shops. The number fell by {p} percent. How many shops are there now?", str(base - x), "shops", tr


def f_convert(r):
    v = r.random(); who = r.choice(NAMES)
    if v < 0.2:
        k = r.randint(2, 400)
        return f"{who} drives {k} kilometres. How many metres is that?", str(k * 1000), "m", fin(r, [f"One kilometre is 1,000 metres, so {k} × 1,000 = {k*1000}."], str(k * 1000), "metres")
    if v < 0.4:
        h = r.randint(2, 48); m = r.choice([0, 15, 30, 45])
        if m:
            tr = fin(r, [f"{h} hours is {h} × 60 = {h*60} minutes.", f"Add the {m} minutes: {h*60} + {m} = {h*60+m}."], str(h * 60 + m), "minutes")
            return f"A flight takes {h} hours and {m} minutes. How many minutes is that in total?", str(h * 60 + m), "min", tr
        return f"How many minutes are there in {h} hours?", str(h * 60), "min", fin(r, [f"One hour is 60 minutes, so {h} × 60 = {h*60}."], str(h * 60), "minutes")
    if v < 0.55:
        w = r.randint(2, 52); d = r.randint(0, 6)
        if d:
            tr = fin(r, [f"{w} weeks is {w} × 7 = {w*7} days.", f"Add the {d} days: {w*7} + {d} = {w*7+d}."], str(w * 7 + d), "days")
            return f"A course runs for {w} weeks and {d} days. How many days is that?", str(w * 7 + d), "days", tr
        return f"How many days are there in {w} weeks?", str(w * 7), "days", fin(r, [f"One week is 7 days, so {w} × 7 = {w*7}."], str(w * 7), "days")
    if v < 0.7:
        m = 60 * r.randint(2, 40)
        return f"{who} worked {m} minutes this week. How many hours is that?", str(m // 60), "hours", fin(r, [f"There are 60 minutes in an hour: {m} / 60 = {m//60}."], str(m // 60), "hours")
    if v < 0.85:
        c = 100 * r.randint(2, 500)
        return f"A path is {c} centimetres long. How many metres is that?", str(c // 100), "m", fin(r, [f"There are 100 centimetres in a metre: {c} / 100 = {c//100}."], str(c // 100), "metres")
    g = 1000 * r.randint(2, 60)
    return f"A sack weighs {g} grams. How many kilograms is that?", str(g // 1000), "kg", fin(r, [f"There are 1,000 grams in a kilogram: {g} / 1,000 = {g//1000}."], str(g // 1000), "kilograms")


def f_date(r):
    v = r.random(); y = r.randint(2001, 2021)
    if v < 0.4:
        m = r.randint(1, 12); dt = date(y, m, r.randint(1, 20)); n = r.randint(3, 40); e = dt + timedelta(days=n)
        w, rem = divmod(n, 7); start = WEEKDAYS[dt.weekday()]
        steps = [f"{n} days is {w} full weeks and {rem} days ({w} × 7 = {w*7}, {n} - {w*7} = {rem}).",
                 f"Full weeks land on the same weekday, so count {rem} days on from {start}: {WEEKDAYS[e.weekday()]}." if rem else
                 f"Full weeks land on the same weekday, so it is still a {start}."]
        return (f"If {dmy(dt)} is a {start}, what day of the week is {n} days later?", WEEKDAYS[e.weekday()], "",
                fin(r, steps, WEEKDAYS[e.weekday()]))
    if v < 0.7:
        m = r.randint(1, 11); a = date(y, m, r.randint(1, 28)); b = a + timedelta(days=r.randint(5, 60)); n = (b - a).days
        if a.month == b.month:
            steps = [f"Both dates are in {calendar.month_name[m]}: {b.day} - {a.day} = {n}."]
        else:
            last = calendar.monthrange(a.year, a.month)[1]; first_part = last - a.day; steps = [
                f"{calendar.month_name[a.month]} has {last} days, so from {dmy(a)} to the end of the month is {last} - {a.day} = {first_part} days."]
            cur = date(a.year, a.month, last) + timedelta(days=1); acc = first_part
            while cur.month != b.month or cur.year != b.year:
                ml = calendar.monthrange(cur.year, cur.month)[1]; acc += ml
                steps.append(f"All of {calendar.month_name[cur.month]}: {ml} more days, running total {acc}."); cur = date(cur.year, cur.month, ml) + timedelta(days=1)
            steps.append(f"Then {b.day} days into {calendar.month_name[b.month]}: {acc} + {b.day} = {acc + b.day}.")
        return f"How many days are there from {dmy(a)} to {dmy(b)}?", str(n), "days", fin(r, steps, str(n), "days")
    m = r.randint(1, 12); d = r.randint(1, 25); last = calendar.monthrange(y, m)[1]
    tr = fin(r, [f"{calendar.month_name[m]} {y} has {last} days.", f"After the {d}th there are {last} - {d} = {last-d} days left."], str(last - d), "days")
    return f"Today is {d} {calendar.month_name[m]} {y}. How many days are left in the month after today?", str(last - d), "days", tr


def f_order(r):
    k = r.randint(3, 5); ppl = r.sample(NAMES, k); more, less, sup, inf = r.choice(ORD_RELATIONS)
    order = ppl[:]; r.shuffle(order)          # order[0] is the greatest
    facts = []
    for i in range(k - 1):
        a, b = order[i], order[i + 1]
        facts.append(f"{a} is {more} than {b}." if r.random() < 0.6 else f"{b} is {less} than {a}.")
    r.shuffle(facts)
    ask_sup = r.random() < 0.5
    q = " ".join(facts) + f" Who is the {sup if ask_sup else inf}?"
    chain = f" > ".join(order)
    ans = order[0] if ask_sup else order[-1]
    tr = fin(r, [f"Put them in order from {sup} to {inf} using each statement: {chain}.",
                 f"The {sup if ask_sup else inf} is at the {'start' if ask_sup else 'end'} of that line."], ans)
    return q, ans, "", tr


def f_count(r):
    v = r.random()
    if v < 0.3:
        d = r.choice([3, 4, 6, 7, 8, 9, 11, 12, 13, 15]); lo = r.randint(1, 200); hi = lo + r.randint(20, 150)
        first = ((lo + d - 1) // d) * d; lastm = (hi // d) * d; cnt = (lastm - first) // d + 1 if lastm >= first else 0
        tr = fin(r, [f"The first multiple of {d} at or after {lo} is {first}; the last at or before {hi} is {lastm}.",
                     f"From {first} to {lastm} in steps of {d}: ({lastm} - {first}) / {d} + 1 = {cnt}."], str(cnt))
        return f"How many whole numbers from {lo} to {hi} are divisible by {d}?", str(cnt), "", tr
    if v < 0.55:
        n = r.randint(4, 30); h = n * (n - 1) // 2
        tr = fin(r, [f"Each of the {n} people shakes {n-1} hands, which counts every handshake twice: {n} × {n-1} = {n*(n-1)}.",
                     f"Halve it: {n*(n-1)} / 2 = {h}."], str(h))
        return f"{n} people at a meeting each shake hands once with every other person. How many handshakes is that?", str(h), "", tr
    if v < 0.8:
        n = r.randint(20, 400); one = 9; two = min(n, 99) - 9; three = max(0, n - 99); digits = one + 2 * two + 3 * three
        steps = [f"Pages 1–9: 9 one-digit numbers, 9 digits.", f"Pages 10–{min(n, 99)}: {two} two-digit numbers, {2*two} digits."]
        if three:
            steps.append(f"Pages 100–{n}: {three} three-digit numbers, {3*three} digits.")
        steps.append(f"Total: {' + '.join(str(x) for x in ([9, 2*two] + ([3*three] if three else [])))} = {digits}.")
        return f"A book's pages are numbered from 1 to {n}. How many digits are printed in total?", str(digits), "", fin(r, steps, str(digits))
    n = r.randint(2, 12); m = r.randint(2, 12)
    tr = fin(r, [f"Every colour can go with every size: {n} × {m} = {n*m}."], str(n * m))
    return f"A shirt comes in {n} colours and {m} sizes. How many different colour-and-size combinations are there?", str(n * m), "", tr


def f_average(r):
    v = r.random()
    if v < 0.4:
        k = r.randint(3, 5); mean = r.randint(5, 40); xs = [mean] * k
        for _ in range(k * 2):
            i, j = r.sample(range(k), 2); d = r.randint(1, 5); xs[i] += d; xs[j] -= d
        if min(xs) < 1:
            xs = [mean] * k
        s = sum(xs)
        tr = fin(r, [f"Add them: {' + '.join(str(x) for x in xs)} = {s}.", f"Divide by how many there are: {s} / {k} = {s//k}."], str(s // k))
        return f"What is the average of {', '.join(str(x) for x in xs[:-1])} and {xs[-1]}?", str(s // k), "", tr
    if v < 0.7:
        k = r.randint(3, 5); mean = r.randint(10, 40); xs = [r.randint(mean - 8, mean + 8) for _ in range(k - 1)]
        missing = mean * k - sum(xs)
        if missing < 1:
            xs = [mean] * (k - 1); missing = mean
        tr = fin(r, [f"An average of {mean} over {k} scores means they total {mean} × {k} = {mean*k}.",
                     f"The known scores add to {' + '.join(str(x) for x in xs)} = {sum(xs)}.",
                     f"The missing score is {mean*k} - {sum(xs)} = {missing}."], str(missing))
        return (f"{r.choice(NAMES)}'s scores were {', '.join(str(x) for x in xs)}, and the average of all {k} scores was {mean}. "
                f"What was the {['third', 'fourth', 'fifth'][k - 3]} score?", str(missing), "", tr)
    n = r.randint(20, 99); d = r.randint(3, 9); q_, rem = divmod(n, d)
    tr = fin(r, [f"{d} children can each take {q_}: {d} × {q_} = {d*q_}.", f"Left over: {n} - {d*q_} = {rem}."], str(rem))
    return f"{n} sweets are shared equally among {d} children. How many sweets are left over?", str(rem), "", tr


FAMILIES = {"shop": f_shop, "rate": f_rate, "percent": f_percent, "convert": f_convert,
            "date": f_date, "order": f_order, "count": f_count, "average": f_average}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=3000)
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--out", default=OUT)
    ap.add_argument("--seed-out", default=OUT_SEED)
    a = ap.parse_args()
    r = random.Random(a.seed)
    rows, seen = [], set()
    fams = list(FAMILIES)
    misses = {k: 0 for k in fams}             # a family with few distinct prompts drops out when exhausted
    while len(rows) < a.n and fams:
        fam = fams[len(rows) % len(fams)]
        q, ans, unit, trace = FAMILIES[fam](r)
        if q in seen:
            misses[fam] += 1
            if misses[fam] > 200:
                fams.remove(fam)
            continue
        misses[fam] = 0
        seen.add(q)
        rows.append({"kind": "reasoning", "family": fam, "prompt": q + SUFFIX, "answer": ans, "unit": unit, "trace": trace})
    with io.open(a.out, "w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")
    with io.open(a.seed_out, "w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps({"kind": "reasoning-gen", "family": row["family"],
                                "messages": [{"role": "user", "content": row["prompt"]}, {"role": "assistant", "content": row["trace"]}]},
                               ensure_ascii=False) + "\n")
    # self-checks: every key round-trips through the matcher, and every program trace passes its own checker
    bad = [x for x in rows if not answer_matches("Answer: " + x["answer"], x["answer"])]
    bad_tr = [x for x in rows if not answer_matches(x["trace"], x["answer"])]
    per = {k: sum(1 for x in rows if x["family"] == k) for k in FAMILIES}
    print(f"written {a.out} + {a.seed_out}: {len(rows)} rows {per}; matcher self-check failures: {len(bad)}; trace check failures: {len(bad_tr)}")
    for x in bad_tr[:3]:
        print("  BAD TRACE:", x["prompt"][:80], "|", x["trace"][-80:])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
