"""Verifiable reasoning problems with program-computed keys (O-45 #3, Eric's lever #2; D-93 next mix).

Every problem here is generated by a program that also computes the answer, so a training signal
needs no teacher and no licence question: the model's own trace is kept (STaR, scripts/star_sample.py)
or rewarded (train_grpo.py, kind "reasoning") only when its final answer matches the key. Eight
families, integer answers by construction, so a match is exact:

  shop        n items at a price, a discount or a note to pay with -> total / change
  rate        speed-time-distance, work rates, unit prices (integer results)
  percent     percent of / increase / decrease, chosen so the result is whole
  convert     metric and time conversions (km->m, h->min, weeks->days, ...)
  date        days between two dates, weekday of date + N days, days left in a month
  order       three-to-five-person comparisons (taller / older / earlier) -> who is the extreme
  count       small counting: multiples in a range, digits, pages numbered, handshakes
  average     mean of a small list, missing value given a mean, remainder problems

    python sft/build_reasoning_set.py [--n 3000] [--seed 7]   -> sft/grpo_reasoning.jsonl

Row: {"kind": "reasoning", "family": ..., "prompt": ..., "answer": "<canonical string>", "unit": ...}
The answer is matched by evals-style final-line parsing (see answer_matches below), shared with the
GRPO reward and the sampler so the three never disagree.
"""
from __future__ import annotations

import argparse
import calendar
import io
import json
import os
import random
import re
from datetime import date, timedelta

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "sft", "grpo_reasoning.jsonl")

NAMES = ["Ana", "Ben", "Carla", "Dev", "Elena", "Farid", "Grace", "Hugo", "Iris", "Jonas", "Kira", "Leo",
         "Maya", "Nils", "Omar", "Priya", "Quinn", "Rosa", "Sam", "Tara", "Uma", "Vik", "Wen", "Yara", "Zoe"]
ITEMS = [("notebook", 3, 12), ("pen", 2, 4), ("loaf of bread", 2, 5), ("ticket", 8, 40), ("mug", 4, 15),
         ("apple", 2, 3), ("book", 6, 30), ("candle", 2, 9), ("plant", 5, 25), ("bus ticket", 2, 6)]
PLURAL = {"loaf of bread": "loaves of bread"}


def pl(n: int, item: str) -> str:
    return f"{n} {item}" if n == 1 else f"{n} {PLURAL.get(item, item + 's')}"
WEEKDAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
ORD_RELATIONS = [("taller", "shorter", "tallest", "shortest"), ("older", "younger", "oldest", "youngest"),
                 ("faster", "slower", "fastest", "slowest"), ("heavier", "lighter", "heaviest", "lightest")]


# ---- the shared matcher: final answer = the LAST number (or word) in the text, after "Answer:" if present ----
def final_answer(text: str) -> str:
    """The model's final answer: what follows the last 'Answer:' if any, else the last number in the text."""
    t = text.strip()
    m = list(re.finditer(r"(?i)answer\s*[:=]\s*([^\n]+)", t))
    if m:
        t = m[-1].group(1)
    nums = re.findall(r"-?\d[\d,]*(?:\.\d+)?", t)
    if nums:
        return nums[-1].replace(",", "")
    words = re.findall(r"[A-Za-z]+", t)
    return words[-1] if words else ""


def answer_matches(text: str, answer: str) -> bool:
    got = final_answer(text)
    if not got:
        return False
    if re.fullmatch(r"-?\d+(?:\.\d+)?", answer):
        try:
            return abs(float(got) - float(answer)) < 1e-6
        except ValueError:
            return False
    return got.lower() == answer.lower()


# ---- families -------------------------------------------------------------------------------------------
def f_shop(r):
    n1 = r.randint(2, 9); it1, lo, hi = r.choice(ITEMS); p1 = r.randint(lo, hi)
    v = r.random()
    if v < 0.4:
        n2 = r.randint(1, 6); it2, lo2, hi2 = r.choice([i for i in ITEMS if i[0] != it1]); p2 = r.randint(lo2, hi2)
        total = n1 * p1 + n2 * p2
        q = f"{r.choice(NAMES)} buys {pl(n1, it1)} at {p1} dollars each and {pl(n2, it2)} at {p2} dollars each. How much is that in total, in dollars?"
        return q, str(total), "dollars"
    if v < 0.7:
        total = n1 * p1; note = next(x for x in (20, 50, 100, 200, 500) if x >= total + 1)
        q = f"{r.choice(NAMES)} buys {pl(n1, it1)} at {p1} dollars each and pays with a {note}-dollar note. How much change is due, in dollars?"
        return q, str(note - total), "dollars"
    total = n1 * p1; off = r.choice([d for d in (5, 10, 20, 25, 50) if (total * d) % 100 == 0] or [50])
    q = f"{pl(n1, it1)} cost {p1} dollars each, and the shop takes {off} percent off the total. What is the price after the discount, in dollars?"
    return q, str(total - total * off // 100), "dollars"


def f_rate(r):
    v = r.random()
    if v < 0.35:
        sp = r.choice([30, 40, 45, 50, 60, 80]); h = r.randint(2, 7)
        return f"A train travels at {sp} kilometres per hour for {h} hours. How far does it go, in kilometres?", str(sp * h), "km"
    if v < 0.6:
        sp = r.choice([4, 5, 6, 8, 10, 12]); d = sp * r.randint(2, 9)
        return f"{r.choice(NAMES)} cycles {d} kilometres at a steady {sp} kilometres per hour. How many hours does it take?", str(d // sp), "hours"
    if v < 0.8:
        per = r.randint(2, 9); mins = r.choice([10, 15, 20, 30, 60]); total = mins * r.randint(2, 6)
        return f"A machine makes {per} parts every {mins} minutes. How many parts does it make in {total} minutes?", str(per * (total // mins)), "parts"
    n = r.randint(2, 8); unit = r.randint(2, 15); total = n * unit
    return f"{pl(n, r.choice(ITEMS)[0]).replace(' ', ' identical ', 1)} cost {total} dollars altogether. What does one cost, in dollars?", str(unit), "dollars"


def f_percent(r):
    v = r.random()
    base = r.choice([20, 40, 50, 60, 80, 120, 150, 200, 240, 300, 400, 500])
    if v < 0.4:
        p = r.choice([d for d in (5, 10, 15, 20, 25, 30, 40, 50, 75) if (base * d) % 100 == 0])
        return f"What is {p} percent of {base}?", str(base * p // 100), ""
    if v < 0.7:
        p = r.choice([d for d in (10, 20, 25, 50) if (base * d) % 100 == 0])
        return f"A jacket costs {base} dollars. Its price goes up by {p} percent. What is the new price, in dollars?", str(base + base * p // 100), "dollars"
    p = r.choice([d for d in (10, 20, 25, 50) if (base * d) % 100 == 0])
    return f"A town had {base} shops. The number fell by {p} percent. How many shops are there now?", str(base - base * p // 100), "shops"


def f_convert(r):
    v = r.random()
    who = r.choice(NAMES)
    if v < 0.2:
        k = r.randint(2, 400); return f"{who} drives {k} kilometres. How many metres is that?", str(k * 1000), "m"
    if v < 0.4:
        h = r.randint(2, 48); m = r.choice([0, 15, 30, 45])
        return (f"A flight takes {h} hours and {m} minutes. How many minutes is that in total?" if m else f"How many minutes are there in {h} hours?"), str(h * 60 + m), "min"
    if v < 0.55:
        w = r.randint(2, 52); d = r.randint(0, 6)
        return (f"A course runs for {w} weeks and {d} days. How many days is that?" if d else f"How many days are there in {w} weeks?"), str(w * 7 + d), "days"
    if v < 0.7:
        m = 60 * r.randint(2, 40); return f"{who} worked {m} minutes this week. How many hours is that?", str(m // 60), "hours"
    if v < 0.85:
        c = 100 * r.randint(2, 500); return f"A path is {c} centimetres long. How many metres is that?", str(c // 100), "m"
    g = 1000 * r.randint(2, 60); return f"A sack weighs {g} grams. How many kilograms is that?", str(g // 1000), "kg"


def f_date(r):
    v = r.random()
    y = r.randint(2001, 2021)
    if v < 0.4:
        m = r.randint(1, 12); d1 = r.randint(1, 20); d2 = d1 + r.randint(3, 8)
        dt = date(y, m, d1); n = r.randint(3, 40); e = dt + timedelta(days=n)
        return (f"If {dt.strftime('%d %B %Y').lstrip('0')} is a {WEEKDAYS[dt.weekday()]}, what day of the week is {n} days later?",
                WEEKDAYS[e.weekday()], "")
    if v < 0.7:
        m = r.randint(1, 11); a = date(y, m, r.randint(1, 28)); b = a + timedelta(days=r.randint(5, 60))
        return (f"How many days are there from {a.strftime('%d %B %Y').lstrip('0')} to {b.strftime('%d %B %Y').lstrip('0')}?", str((b - a).days), "days")
    m = r.randint(1, 12); d = r.randint(1, 25); last = calendar.monthrange(y, m)[1]
    return f"Today is {d} {calendar.month_name[m]} {y}. How many days are left in the month after today?", str(last - d), "days"


def f_order(r):
    k = r.randint(3, 5); ppl = r.sample(NAMES, k); more, less, sup, inf = r.choice(ORD_RELATIONS)
    order = ppl[:]; r.shuffle(order)          # order[0] is the greatest
    facts = []
    for i in range(k - 1):
        a, b = order[i], order[i + 1]
        facts.append(f"{a} is {more} than {b}." if r.random() < 0.6 else f"{b} is {less} than {a}.")
    r.shuffle(facts)
    ask_sup = r.random() < 0.5
    q = " ".join(facts) + f" Who is the {sup if ask_sup else inf}?"
    return q, (order[0] if ask_sup else order[-1]), ""


def f_count(r):
    v = r.random()
    if v < 0.3:
        d = r.choice([3, 4, 6, 7, 8, 9, 11, 12]); lo = r.choice([1, 10, 20, 50]); hi = lo + r.choice([30, 50, 99])
        cnt = sum(1 for x in range(lo, hi + 1) if x % d == 0)
        return f"How many whole numbers from {lo} to {hi} are divisible by {d}?", str(cnt), ""
    if v < 0.55:
        n = r.randint(4, 12); return f"{n} people at a meeting each shake hands once with every other person. How many handshakes is that?", str(n * (n - 1) // 2), ""
    if v < 0.8:
        n = r.randint(20, 150); digits = sum(len(str(x)) for x in range(1, n + 1))
        return f"A book's pages are numbered from 1 to {n}. How many digits are printed in total?", str(digits), ""
    n = r.randint(3, 9); m = r.randint(3, 9)
    return f"A shirt comes in {n} colours and {m} sizes. How many different colour-and-size combinations are there?", str(n * m), ""


def f_average(r):
    v = r.random()
    if v < 0.4:
        k = r.randint(3, 5); mean = r.randint(5, 40); xs = [mean] * k
        for _ in range(k * 2):
            i, j = r.sample(range(k), 2); d = r.randint(1, 5); xs[i] += d; xs[j] -= d
        if min(xs) < 1:
            xs = [mean] * k
        return f"What is the average of {', '.join(str(x) for x in xs[:-1])} and {xs[-1]}?", str(sum(xs) // k), ""
    if v < 0.7:
        k = r.randint(3, 5); mean = r.randint(10, 40); xs = [r.randint(mean - 8, mean + 8) for _ in range(k - 1)]
        missing = mean * k - sum(xs)
        if missing < 1:
            xs = [mean] * (k - 1); missing = mean
        return (f"{r.choice(NAMES)}'s scores were {', '.join(str(x) for x in xs)}, and the average of all {k} scores was {mean}. "
                f"What was the {['third', 'fourth', 'fifth'][k - 3]} score?", str(missing), "")
    n = r.randint(20, 99); d = r.randint(3, 9)
    return f"{n} sweets are shared equally among {d} children. How many sweets are left over?", str(n % d), ""


FAMILIES = {"shop": f_shop, "rate": f_rate, "percent": f_percent, "convert": f_convert,
            "date": f_date, "order": f_order, "count": f_count, "average": f_average}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=3000)
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--out", default=OUT)
    a = ap.parse_args()
    r = random.Random(a.seed)
    rows, seen = [], set()
    fams = list(FAMILIES)
    misses = {k: 0 for k in fams}             # a family with few distinct prompts (convert) drops out when exhausted
    while len(rows) < a.n and fams:
        fam = fams[len(rows) % len(fams)]
        q, ans, unit = FAMILIES[fam](r)
        if q in seen:
            misses[fam] += 1
            if misses[fam] > 200:
                fams.remove(fam)
            continue
        misses[fam] = 0
        seen.add(q)
        rows.append({"kind": "reasoning", "family": fam, "prompt": q + " Think it through step by step, then end with 'Answer: <value>'.",
                     "answer": ans, "unit": unit})
    with io.open(a.out, "w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")
    # self-check: every key round-trips through the matcher on its own canonical form
    bad = [x for x in rows if not answer_matches("Answer: " + x["answer"], x["answer"])]
    per = {k: sum(1 for x in rows if x["family"] == k) for k in FAMILIES}
    print(f"written {a.out}: {len(rows)} rows {per}; matcher self-check failures: {len(bad)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
