"""Factual source passages on crypto/blockchain fundamentals, written by hand for
grounding DeepSeek's synthetic Q&A generation (scripts/generate_synthetic_crypto.py).

Why passages instead of asking DeepSeek to explain from its own memory: a smoke
test showed the 1.5B distill get UTXO mechanics factually wrong when generating
freely. Rather than trust an unverified model's parametric memory for the exact
subject matter Pagouro claims to handle honestly, each fact is written and
checked here, and DeepSeek's job is narrowed to producing a well-framed Q&A pair
FROM a given true passage, not authoring facts of its own. This is the same
grounding discipline as everything else in this project.

Every passage is intentionally conservative: mechanism and definition, not price
history, predictions, or contested claims (those belong in the deflection-style
SFT set, argued explicitly, not asserted as fact here).
"""

PASSAGES = [
    ("bitcoin-utxo", "A UTXO (unspent transaction output) is the output of a Bitcoin transaction that has not yet been spent. A wallet's balance is the sum of all UTXOs controlled by its keys, not a single stored number in an account."),
    ("bitcoin-pow", "Proof of work is a mechanism where network participants (miners) compete to find a number (a nonce) that, combined with a block's contents, produces a hash below a target value. Finding it is computationally expensive; verifying it once found is cheap. This asymmetry is what lets the network agree on one history without a central authority."),
    ("bitcoin-halving", "Bitcoin's mining reward is cut in half approximately every 210,000 blocks, roughly every four years. This halving schedule is fixed in the protocol and is what makes the total supply approach a hard cap of 21 million coins, issued on a known, decreasing schedule rather than at a constant or discretionary rate."),
    ("bitcoin-difficulty", "Bitcoin adjusts its mining difficulty roughly every two weeks (2016 blocks) so that blocks continue to be found on average every 10 minutes, regardless of how much total computing power (hashrate) is pointed at the network. If more miners join and blocks come faster than 10 minutes on average, difficulty rises; if miners leave, it falls."),
    ("public-private-key", "In public-key cryptography, a private key is a secret number only its holder should know, and a public key is mathematically derived from it but cannot be reversed back to the private key. The private key can produce a signature that anyone holding the public key can verify came from that key, without ever revealing the private key itself."),
    ("bitcoin-address", "A Bitcoin address is a shortened, encoded representation derived from a public key (typically hashed for compactness and error-checking), used as the destination for a payment. It is safe to share publicly; funds sent to it can only be spent by whoever controls the matching private key."),
    ("blockchain-block", "A block in a blockchain is a batch of transactions bundled together along with a reference to the cryptographic hash of the previous block. Because each block's hash depends on its own contents plus the previous block's hash, altering any earlier block changes its hash and breaks the link to every block that comes after it, making tampering with history evident."),
    ("merkle-tree", "A Merkle tree is a structure that combines many pieces of data (like all transactions in a block) into a single hash by repeatedly hashing pairs together up to one 'root' hash. It lets someone verify that a specific transaction is included in a block by checking a short path of hashes, without needing to download every transaction in that block."),
    ("51-percent-attack", "A 51% attack refers to a scenario where a single entity or coordinated group controls more than half of a proof-of-work network's total mining power. With that majority, they could in principle reverse their own recent transactions (double-spend) or exclude certain transactions from blocks, though rewriting old, deeply buried history becomes exponentially harder the further back it is."),
    ("mempool", "The mempool (memory pool) is the set of transactions a node has received and considers valid but that have not yet been included in a mined block. Miners typically select transactions from their mempool to include in the next block, often prioritizing those offering higher fees."),
    ("double-spend-problem", "The double-spend problem is the risk that a digital token, being just data, could be copied and spent more than once. Bitcoin's blockchain solves this by having the network publicly agree, through proof-of-work consensus, on a single ordered history of transactions, so a second attempt to spend an already-spent output is rejected by the network."),
    ("smart-contract", "A smart contract is code deployed on a blockchain (notably Ethereum) that executes automatically when its conditions are met, with its logic and execution enforced by the network's consensus rather than by a centralized server. It can hold funds, enforce agreements, or coordinate other contracts, and once deployed, its code typically cannot be changed."),
    ("proof-of-stake", "Proof of stake is a consensus mechanism where the right to propose and validate new blocks is allocated based on how much cryptocurrency a participant has locked up (staked) as collateral, rather than on computational work. Misbehavior can result in a portion of that stake being forfeited (slashed), which replaces energy expenditure as the cost of attempting to cheat."),
    ("layer-2-lightning", "The Lightning Network is a 'layer 2' system built on top of Bitcoin that lets participants open payment channels with each other, exchange many transactions instantly and privately off the main blockchain, and only settle the net result on-chain when the channel closes. It trades some trust and liquidity requirements for far higher transaction throughput and lower fees than the base layer."),
    ("cold-vs-hot-wallet", "A 'hot' wallet keeps its private keys on an internet-connected device, making it convenient for frequent transactions but exposed to remote attacks. A 'cold' wallet keeps private keys on a device that never connects to the internet (like a hardware wallet or paper backup), trading convenience for much stronger protection against remote theft."),
    ("seed-phrase", "A seed phrase (or recovery phrase) is a sequence of words, typically 12 or 24, that encodes the master private key material for a wallet. Anyone possessing the seed phrase can recreate the wallet and its keys and spend its funds, which is why it is treated as equivalent to the funds themselves and never entered into an online form or shared with anyone."),
    ("fork-hard-soft", "A fork is a change to a blockchain's rules. A soft fork tightens the rules in a way that old, unupgraded nodes still recognize new blocks as valid, so the chain can stay unified even if not everyone upgrades. A hard fork changes the rules in a way old nodes reject, and if not everyone adopts it, the network can permanently split into two separate chains."),
    ("stablecoin", "A stablecoin is a cryptocurrency designed to hold a stable value, usually pegged to a fiat currency like the US dollar. Mechanisms vary: some are backed by holding actual dollar reserves, some by other crypto assets held as over-collateralization, and some by an algorithmic supply adjustment, each with different failure modes if the peg is stressed."),
    ("gas-fees", "On Ethereum, 'gas' measures the computational work a transaction or smart contract call requires, and users pay a gas fee, priced in the network's native currency, to compensate validators for that work. Fees rise when network demand for block space is high and fall when it is low, similar to how Bitcoin's transaction fees respond to mempool congestion."),
    ("dao", "A DAO (decentralized autonomous organization) is a group coordinated through rules encoded in smart contracts and governed by token-holder voting, rather than through a traditional legal entity's management hierarchy. Decisions like spending shared funds or changing rules are typically proposed and voted on on-chain, with outcomes executed automatically by the contract code."),
    ("zero-knowledge-proof", "A zero-knowledge proof lets one party prove a statement is true to another party without revealing any information beyond the fact that the statement is true. In blockchains, this allows verifying that a transaction is valid (for example, that a sender has sufficient balance) without revealing the sender's identity, balance, or the transaction amount."),
    ("satoshi-unit", "A satoshi (often shortened to 'sat') is the smallest unit of bitcoin, defined as one hundred-millionth of a single bitcoin (0.00000001 BTC). It exists so bitcoin can be divided into very small amounts for pricing and transactions, similar to how a currency's smallest coin is a fraction of its main unit."),
    ("node-full-vs-light", "A full node downloads and independently verifies the entire blockchain and every rule of the protocol, giving it the strongest guarantee that it is following the real, valid chain without trusting anyone else. A light (SPV) node only downloads block headers and trusts full nodes for transaction details, trading some verification strength for far lower storage and bandwidth requirements."),
    ("bitcoin-whitepaper-core-claim", "Bitcoin's original whitepaper, published under the name Satoshi Nakamoto in 2008, proposed a peer-to-peer electronic cash system that lets online payments be sent directly between parties without going through a financial institution, solving the double-spend problem through a network that timestamps transactions by hashing them into an ongoing chain of proof-of-work."),
    ("custodial-vs-noncustodial", "A custodial service (like most exchanges) holds a user's private keys on their behalf, meaning the user must trust that service to safeguard funds and allow withdrawals. A non-custodial wallet gives the user direct, sole control of their own private keys, which removes counterparty risk but also removes any recourse if the user loses access."),
    ("token-vs-coin", "A native coin (like bitcoin or ether) is the asset built into and secured directly by its own blockchain's consensus mechanism. A token is an asset issued on top of an existing blockchain (commonly via a smart contract standard), relying on that underlying chain's security rather than having its own independent network."),
    ("consensus-mechanism-purpose", "A consensus mechanism is the set of rules a decentralized network uses to agree on a single, shared version of the transaction history without any single party being in charge. Proof of work and proof of stake are the two most common approaches, differing mainly in what cost they impose on a participant who tries to cheat the process."),
    ("orphan-block", "An orphan (or stale) block is a validly mined block that ends up excluded from the main chain because another block at the same height was accepted by more of the network first, often due to two miners finding a valid block at nearly the same time. The transactions in an orphaned block typically return to the mempool to be included in a later block."),
    ("defi", "DeFi (decentralized finance) refers to financial services, such as lending, borrowing, and trading, implemented through smart contracts on a blockchain rather than through banks or brokerages. Users interact directly with the code and typically retain custody of their own assets throughout, in contrast to depositing funds with a traditional financial intermediary."),
    ("airdrop", "A crypto airdrop is a distribution of a new token to a set of wallet addresses, often chosen based on past activity (such as having used a related protocol), without the recipients paying for it directly. Projects use airdrops to distribute ownership or governance rights broadly and to reward early users of a network or application."),
]
